spring:
  application:
    name: bms
  datasource:
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: mysql
  jooq:
    sql-dialect: MYSQL